G4HepEm/G4HepEmRun/src/G4HepEmElectronManager.cc
I'm not really sure about this one, but I *think* the call intends to the get cross section for the current particle, which may be a positron.
=> Use PositronData for call to GetRestMacXSec

G4HepEm/G4HepEmData/include/G4HepEmData.hh, G4HepEm/G4HepEmData/include/G4HepEmSBTableData.hh, G4HepEm/G4HepEmData/src/G4HepEmData.cc, G4HepEm/G4HepEmData/src/G4HepEmData.cu, G4HepEm/G4HepEmData/src/G4HepEmElectronData.cu, G4HepEm/G4HepEmData/src/G4HepEmSBTableData.cc, G4HepEm/G4HepEmData/src/G4HepEmSBTableData.cu
These sampling tables are used (only) at run-time in `G4HepEm` at the final state generation of the low energy e-/e+ model (SB) for bremsstrahlung photon emission.  These makes possible a rejection free sampling of the emitted photon energy (according to the **Seltzer-Berger DCS**-s, i.e. below 1 [GeV] primary energy. Note, that this is special for `G4HepEm` since the corresponding `Geant4` model, `G4SeltzerBergerModel` utilises a rejection based sampling requiring even an expensive 2D interpolation at run-time.
=> Implemented copy of the G4HepEm Seltzer-Berger brem.  sampling tables to the device

G4HepEm/G4HepEmData/src/G4HepEmElectronData.cu, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronTrack.hh, G4HepEm/G4HepEmRun/include/G4HepEmTrack.hh
The idea is that it's possible to reuse most of the code by keeping random numbers out of the computations.
=> Changes to reuse G4HepEmElectronManager::HowFar on the GPU

G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionBrem.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionBrem.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionIoni.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionIoni.icc, G4HepEm/G4HepEmRun/include/G4HepEmMacros.hh, G4HepEm/G4HepEmRun/include/G4HepEmRandomEngine.hh, G4HepEm/G4HepEmRun/include/G4HepEmTLData.hh, G4HepEm/include/G4HepEmCLHEPRandomEngine.hh, G4HepEm/include/G4HepEmProcess.hh, G4HepEm/include/G4HepEmRunManager.hh, G4HepEm/src/G4HepEmProcess.cc, G4HepEm/src/G4HepEmRunManager.cc, apps/tests/ElectronEnergyLoss/TestEnergyLossData.cc, apps/tests/ElectronTargetElementSelector/TestElemSelectorData.cc, apps/tests/ElectronXSections/TestXSectionData.cc, apps/tests/MaterialAndRelated/TestMaterialAndRelated.cc
`G4HepEmRandomEngine` holds a reference to the real engine and two function pointers to generate one random number or fill an array with a given size, respectively. `G4HepEmCLHEPRandomEngine` is a wrapper around `CLHEP::HepRandomEngine` and dispatches to the virtual functions defined in the derived class.
The goal of this abstraction is to decouple the `G4HepEmRun` library from `CLHEP` and pave the way for passing in custom RNG implementations to the final state sampling. This enables further changes to reuse more code on the GPU.
---
Building on this abstraction, make the energy transfer sampling for ionisation and Bremsstrahlung reusable.
=> Abstract RNG into an object with two function pointers

G4HepEm/G4HepEmData/src/G4HepEmSBTableData.cu, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionBrem.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionBrem.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, G4HepEm/G4HepEmRun/include/G4HepEmTrack.hh, G4HepEm/include/G4HepEmRunManager.hh, G4HepEm/src/G4HepEmProcess.cc, apps/tests/testElectronInteractionBrem/CMakeLists.txt, apps/tests/testElectronInteractionBrem/include/Declaration.hh, apps/tests/testElectronInteractionBrem/include/Hist.hh, apps/tests/testElectronInteractionBrem/include/TestBremArgs.hh, apps/tests/testElectronInteractionBrem/src/Implementation.cc, apps/tests/testElectronInteractionBrem/src/SBTableData.cu, apps/tests/testElectronInteractionBrem/src/TestBremArgs.cc, apps/tests/testElectronInteractionBrem/testBrem.cc
The test can generate final states of **e-/e+ bremsstrahlung photon emission** both using the low (**Seltzer-Berger**) and high (**Relativistic**) energy models. The primary particle type, its kinetic energy as well as the target material can be configured by input arguments. Both the native `Geant4` models or the `G4HepEm` interaction implementations can be utilised and selected by providing the appropriate input argument. A simple host vs device consistency test of the `G4HepEmSBTableData` is also available that can also be selected by the appropriate input argument. See more by executing the application with the ``--help`` input argument or ``-h`` flag.
=> Unit/model level test for testing the interaction models for e-/e+ bremsstrahlung photon emission.

G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionBrem.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionBrem.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionIoni.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionIoni.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, apps/tests/testElectronInteractionBrem/src/Implementation.cc
Computations of the post interaction primary and secondary particle directions have been separated out from the main interaction functions (similarly to the energy transfer part) such that they depend only on primitive types (plus the already resolved random-engine). Therefore, even this part of the interaction computations of e-/e+ Ionisation and Bremsstrahlung   
can be now re-used on the device (after marking them and the related functions properly).  A high fraction (>95%) of the interaction computation can now be re-used on the device and only couple of lines, that depend on the actual track representation, need to be implemented.  
Furthermore, the earlier 2 interaction model (SB and RB) for bremsstrahlung have been merged into a single function, reducing further the amount of …
=> Further increase of host side code reusability on the device by modifying the interaction model implementations 

G4HepEm/CMakeLists.txt, G4HepEm/G4HepEmData/CMakeLists.txt, G4HepEm/G4HepEmInit/CMakeLists.txt, G4HepEm/G4HepEmRun/CMakeLists.txt
When integrating G4HepEm into another project and invoking it via `add_subdirectory()`, `CMAKE_SOURCE_DIR` refers to the directory that CMake was started with and various files cannot be found. Move all uses to `CMAKE_CURRENT_SOURCE_DIR` or `PROJECT_SOURCE_DIR`.
=> Avoid using CMAKE_SOURCE_DIR

.github/workflows/cpu_build.yml, CMakeLists.txt, G4HepEm/CMakeLists.txt, G4HepEm/G4HepEmData/CMakeLists.txt, G4HepEm/G4HepEmInit/CMakeLists.txt, G4HepEm/G4HepEmRun/CMakeLists.txt, apps/tests/ElectronXSections/src/Implementation.cc, cmake/G4HepEmConfig.cmake.in, testing/CMakeLists.txt
This is a reasonbly large update to G4HepEm's buildscripts to follow recommendations from modern cmake (e.g. https://cliutils.gitlab.io/modern-cmake/) to improve overall simplicity, readability, and reliability. The primary changes are:
- Always set all policies in used version in supported range
- Use `project(... VERSION)` so there is a version number to check, even if it's not especially meaningful yet.
- Use [`GNUInstallDirs`](https://cmake.org/cmake/help/v3.8/module/GNUInstallDirs.html) module for standardized install locations
- Use "target_..." commands to set [usage requirements](https://cmake.org/cmake/help/v3.8/manual/cmake-buildsystem.7.html#build-specification-and-usage-requirements) on targets and ease their use by both internal and external consumers.
- Use …
=> Modern CMake updates for CPU portion of code/tests

apps/tests/ElectronEnergyLoss/include/Declaration.hh, apps/tests/ElectronEnergyLoss/src/ELossData.cu, apps/tests/ElectronTargetElementSelector/include/Declaration.hh, apps/tests/ElectronTargetElementSelector/src/ElemSelector.cu, apps/tests/ElectronXSections/include/Declaration.hh, apps/tests/ElectronXSections/src/ResMacXSecs.cu, apps/tests/MaterialAndRelated/include/Declaration.hh, apps/tests/testElectronInteractionBrem/include/Declaration.hh
They are only called in the `.cu` files they are implemented in. Move them to the top to make them declared before called. This fixes the build with CUDA + tests enabled in an environment that doesn't have `device_launch_parameters.h` in the include path, which now isn't used anymore.
=> [tests] Remove kernels from header files

testing/ElectronEnergyLoss/CMakeLists.txt, testing/ElectronTargetElementSelector/CMakeLists.txt, testing/ElectronXSections/CMakeLists.txt, testing/MaterialAndRelated/CMakeLists.txt
A very minor update to the CMake/CTests to use the full and recommended signature of `add_test(NAME <testname> COMMAND <command>)`. This form means that any target name (i.e. built in this project) in `<command>` will be resolved by CMake to the full path to that target's executable, and avoids any clashes with the system `PATH` and so on.
=> Use NAME/COMMAND form of add_test

CMakeLists.txt
To match up the default build mode to that of the primary Geant4 dependency, default builds of `G4HepEm` with single mode generators to `Release`. Multiconfig generators like Xcode etc will still use Debug as the default.
No use of Geant4 C++ flags is added _in this PR_ as local testing of `TestEm3` and the `ATLASbar.mac` script show average runtimes with differences dominated by system fluctuations. There is _not yet_ an observable difference with/without `Geant4_CXX_FLAGS`, the build mode fix here providing the real difference.
Fixes: #29
=> Default to Release builds for single-mode generators

G4HepEm/include/G4HepEmProcess.hh, G4HepEm/src/G4HepEmProcess.cc, apps/examples/TestEm3/src/PhysListHepEm.cc
This was required to have appropriate behaviour even with an active field propagation (everything is related to details of the information updates in the general ``Geant4`` stepping loop.)
=> The G4HepEmProcess type has been changed to (Forced) discrete.

G4HepEm/G4HepEmData/src/G4HepEmElectronData.cc, G4HepEm/G4HepEmData/src/G4HepEmGammaData.cc, G4HepEm/G4HepEmInit/src/G4HepEmElectronTableBuilder.cc, G4HepEm/G4HepEmInit/src/G4HepEmGammaTableBuilder.cc
When a target element selector data is not necessary just leave the corresponding dynamic array data pointer to be `nullptr` (and the corresponding number-of-data is equal to 0). See more at the discussion of #41.
=> Update values of the unused dynamic array pointers of the target element selectors.

G4HepEm/G4HepEmData/include/G4HepEmElectronData.hh, G4HepEm/G4HepEmData/include/G4HepEmElementData.hh, G4HepEm/G4HepEmData/include/G4HepEmGammaData.hh, G4HepEm/G4HepEmData/include/G4HepEmMatCutData.hh, G4HepEm/G4HepEmData/include/G4HepEmMaterialData.hh, G4HepEm/G4HepEmData/include/G4HepEmSBTableData.hh, G4HepEm/G4HepEmData/src/G4HepEmData.cc, G4HepEm/G4HepEmData/src/G4HepEmElectronData.cc, G4HepEm/G4HepEmData/src/G4HepEmElementData.cc, G4HepEm/G4HepEmData/src/G4HepEmGammaData.cc, G4HepEm/G4HepEmData/src/G4HepEmMatCutData.cc, G4HepEm/G4HepEmData/src/G4HepEmMaterialData.cc, G4HepEm/G4HepEmData/src/G4HepEmSBTableData.cc, testing/CMakeLists.txt, testing/G4HepEmDataInterfaces/CMakeLists.txt, testing/G4HepEmDataInterfaces/TestG4HepEmDataInterfaces.cc
This is a Draft/WIP PR to add a few simplifications to init/allocation of the G4HepEmData `struct`s. These have come up through the work on (de)serialising these data (to/from JSON using nlohmann_json), but I think will be of use more broadly for working with these structures, hence a separate PR. Marked as Draft and so not for merge yet so @mnovak42 can check the initial working (@hahnjo your input is also welcome!) before I go further.
To that end I've just implemented things for the lowest level `G4HepEmElementData` struct as this nicely illustrates the updates in a simple way, which are:
* Use in-struct initialization of the `fZet` data member of `G4HepEmElemData` to save the loop over the array in `AllocateElementData`.
* I haven't intialized any other data members for now, as only …
=> Simplify allocation/initialization of G4HepEmData structures

G4HepEm/G4HepEmData/include/G4HepEmParameters.hh, G4HepEm/G4HepEmData/include/G4HepEmState.hh, G4HepEm/G4HepEmDataJsonIO/include/G4HepEmDataJsonIO.hh, G4HepEm/G4HepEmDataJsonIO/src/G4HepEmDataJsonIO.cc, G4HepEm/G4HepEmDataJsonIO/src/G4HepEmDataJsonIOImpl.hh
Many G4HepEmRun functions take both G4HepEmData and G4HepEmParameters for their calculations. Clients serializing data will also need to store the parameters with the data for consistency when using the deserialized data.
Add new G4HepEmState struct that is a simple association between pointers to a G4HepEmData instance and a corresponding G4HepEmParameters instance. This is implemented as a simple view of these pointers, and no (de)allocation
is performed or implemented.
Add JSON (de)serialization functions for G4HepEmParameters and G4HepEmState.
Update DataImportExport test to roundtrip G4HepEmState and the held parameters and data.
Fixes: #45
=> Implement G4HepEmState struct to associate parameters and data

apps/examples/TestEm3/src/PhysicsList.cc
G4RadioactiveDecay is deprecated since Geant4 10.6.1 while the replacement is available since version 10.4. Tests show identical
results with `emstandard_opt0`.
=> Replace deprecated G4RadioactiveDecay with G4RadioactiveDecayBase

CMakeLists.txt
Also try target `Geant4::G4clhep-static` if the shared library is not available.
=> Enable linking against static CLHEP

G4HepEm/include/G4HepEmProcess.hh, G4HepEm/src/G4HepEmProcess.cc
This is the simple solution of applying the cuts after the final state sampling. In the future, this process will get more efficient by taking the cuts into account at model level, and for example avoid sampling the direction of a secondary particle.
=> Implement ApplyCuts in G4HepEmProcess

G4HepEm/G4HepEmData/src/G4HepEmElectronData.cc, G4HepEm/G4HepEmData/src/G4HepEmElementData.cc, G4HepEm/G4HepEmData/src/G4HepEmGSTableData.cc, G4HepEm/G4HepEmData/src/G4HepEmGammaData.cc, G4HepEm/G4HepEmData/src/G4HepEmMatCutData.cc, G4HepEm/G4HepEmData/src/G4HepEmMaterialData.cc, G4HepEm/G4HepEmData/src/G4HepEmSBTableData.cc
When implementing the (simplified) photoelectric effect in commit 26f6ead338, I assumed that non-pointer members are automatically copied to the GPU via a `memcpy`. As this was not the case, the new data members were missing and not properly initialized. Change all copy functions to now use a `memcpy` of the data structure to catch newly added fields in the future.
=> Fix data transfer to GPU and make it more resistent

G4HepEm/G4HepEmRun/include/G4HepEmTLData.hh, G4HepEm/G4HepEmRun/src/G4HepEmTLData.cc, G4HepEm/include/G4HepEmProcess.hh, G4HepEm/src/G4HepEmProcess.cc, G4HepEm/src/G4HepEmRunManager.cc
The interaction is only needed in the process, located in the G4HepEm library; the G4HepEmRun library should not depend on Geant4 itself.
=> Move safety helper to G4HepEmProcess

G4HepEm/include/G4HepEmRunManager.hh, G4HepEm/src/G4HepEmRunManager.cc
The method `ClearAll()` attempts to call `Clear()` on all known `G4HepEmRunManager`s. This is dangerous if the workers have been destructed already.
=> Fix destruction of G4HepEmRunManager

G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, G4HepEm/include/G4HepEmNoProcess.hh, G4HepEm/include/G4HepEmProcess.hh, G4HepEm/src/G4HepEmProcess.cc
Some user codes and/or the `Geant4` tracking verbose depend on some information that is set in the `G4Track` during the stepping by the `G4SteppingManager` such as the process that determined the given step, etc. 
Since `G4HepEm` has no individual processes and covers several processes while only the single `G4HepEmProcess` is seen by the `Geant4` framework, the limiter process is always set to this. 
This has been resolved by overwriting the `G4Track` field (actually its post step point field) with a dummy `G4VProcess` pointer that is empty but contains the correct (i.e. same as the real `Geant4`) process names. 
Additional functionality, to obtain these process pointers by name has also been added.
=> Providing information regarding the processes that determined/limited the step inside G4HepEm

.github/workflows/cpu_build.yml
* Use newly built binaries, hosted on GitHub, that are smaller and faster to download.
* Test against Geant4 10.06.p03 and 10.07.p03, with everything in place to extend the list of versions in the future.
=> Overhaul CI testing

G4HepEm/G4HepEmData/include/G4HepEmMaterialData.hh, G4HepEm/G4HepEmInit/src/G4HepEmMaterialInit.cc, G4HepEm/G4HepEmRun/CMakeLists.txt, G4HepEm/G4HepEmRun/include/G4HepEmConstants.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronEnergyLossFluctuation.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronEnergyLossFluctuation.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionIoni.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionUMSC.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, G4HepEm/G4HepEmRun/include/G4HepEmGammaInteractionCompton.icc, G4HepEm/G4HepEmRun/include/G4HepEmGammaInteractionPhotoelectric.icc, G4HepEm/G4HepEmRun/include/G4HepEmInteractionUtils.icc, G4HepEm/G4HepEmRun/include/G4HepEmPositronInteractionAnnihilation.icc, G4HepEm/G4HepEmRun/include/G4HepEmRandomEngine.hh, apps/examples/TestEm3/src/PhysListG4Em.cc, apps/examples/TestEm3/src/PhysListG4EmTracking.cc
The Laszlo's universal model for energy loss fluctuation has been implemented for e-/e+ in `G4HepEm`. The implemented model corresponds to the `G4UniversalFluctuation` model as it is in `Geant4-v11.p01` (its latest public release version, i.e. `Geant4-v11.00`, can also be used for comparisons: see [`G4HepEmElectronEnergyLossFluctuation.icc`](https://github.com/mnovak42/g4hepem/blob/addElossFluct/G4HepEm/G4HepEmRun/include/G4HepEmElectronEnergyLossFluctuation.icc#28) ).
=> Adding energy loss fluctuation. 

G4HepEm/src/G4HepEmProcess.cc
Note, that there are no real processes in `G4HepEm` but some `Geant4` user codes might need to know the type/name of the `G4VProcess` that defined a given step and possible created some (secondary) tracks. So the `G4HepEmProcess` creates a set of empty `G4VProcess`-es with the correct names (e.g. "phot", "compt" and "conv") and sets the *Process defined step* pointer field of the post-step to the appropriate one.
=> Correct the name of the process that defined the step.

G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc
When disabling a combination of MSC and energy loss fluctuation, the compiler warned about some unused variables.
=> Resolve warnings about unused variables

G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronTrack.hh, G4HepEm/include/HepEmTrackingManager.hh, G4HepEm/src/HepEmTrackingManager.cc, G4HepEm/src/TrackingManagerHelper.hh, G4HepEm/src/TrackingManagerHelper.icc
If a step is only limited by MSC, the `HepEmTrackingManager` can re-try the step with the remaining distance to the discrete interaction, without applying energy loss fluctuations and re-computing the cross sections. This option is enabled by default because it provides a small performance benefit, but can be turned off to get results identical to the `G4HepEmProcess`.
=> Add possibility of MSC stepping to HepEmTrackingManager

G4HepEm/G4HepEmData/src/G4HepEmElectronData.cc, G4HepEm/G4HepEmData/src/G4HepEmGammaData.cc
When the host data structure is copied during GPU set up, the host
pointers need to be overwritten to obtain correct device pointers.
=> Correctly initialise GPU pointers.

CMakeLists.txt, G4HepEm/CMakeLists.txt, G4HepEm/G4HepEmData/CMakeLists.txt, G4HepEm/G4HepEmDataJsonIO/CMakeLists.txt, G4HepEm/G4HepEmInit/CMakeLists.txt, G4HepEm/G4HepEmRun/CMakeLists.txt
This is required for integration into experiments.
The general idea is that the targets for static libraries are always suffixed with `-static`, but `ALIAS` targets are added unless we also build shared libraries.
=> Rewrite CMake code to allow both shared and static libs

G4HepEm/G4HepEmInit/include/G4HepEmInitUtils.hh, G4HepEm/G4HepEmInit/src/G4HepEmElectronTableBuilder.cc, G4HepEm/G4HepEmInit/src/G4HepEmGammaTableBuilder.cc, G4HepEm/G4HepEmInit/src/G4HepEmInitUtils.cc
This class has no state, so does not need to be a singleton. Following practice elsewhere in G4HepEM, convert to non-constructable class with only static member functions. 
No other changes, pure tidy.
=> Convert G4HepEmInitUtils to non-singleton

CMakeLists.txt
This is pretty trivial since G4HepEm is already working in systems with code compiled with a mix of C++ standards, but _just in case experiments get picky_, this allows `CMAKE_CXX_STANDARD` to be set at `cmake` time. 
The default of C++11 is retained, the set standard being checked that this minimum requirement is satisfied. CMake will error out if C++98 or otherwise invalid standard is supplied.
=> Allow CMAKE_CXX_STANDARD to be set by user

G4HepEm/G4HepEmInit/include/G4HepEmInitUtils.hh, G4HepEm/G4HepEmInit/src/G4HepEmElectronTableBuilder.cc, G4HepEm/G4HepEmInit/src/G4HepEmGammaTableBuilder.cc, G4HepEm/G4HepEmInit/src/G4HepEmInitUtils.cc
I'm not sure what policy/thoughts on refactoring in G4HepEm are (hence draft status, so feel free to reject!), but this _seemed_ like an obviously one to ensure commonality for the reasonably wide use of energy grids with spacing of points even in `log(E)`. The population of these arrays and ancillary data (log of lower bound, inverse of spacing in `log(E)`) is identical in all the places I could find in `G4HepEmInit`, so that's been factored into a helper function in `G4HepEmInitUtils`, with clients updated to use this. NB: implemented as a `static` function in `G4HepEmInitUtils` in line with #92, but easy to change if needed.
I've only done a rough test using the existing tests for now, but if people think this is useful update I'll check/validate in more depth to be sure.
=> Create function for creation of logarithmic energy grids

G4HepEm/G4HepEmInit/src/G4HepEmInitUtils.cc, G4HepEm/G4HepEmRun/include/G4HepEmRunUtils.hh, G4HepEm/G4HepEmRun/include/G4HepEmRunUtils.icc
Very much along the lines of #93, this separates the spline calculation part of `GetSpline/GetSplineLog` in `G4HepEmInit` and `G4HepEmRun` from the operations extracting the required `x,y,y"` data from the input array(s). These are of course separate libraries, with `G4HepEMRun` required to run on device, so no further unification is intended - the code duplication is fine here, and the current changes reduce that a lot(*). The signature of the new function was chosen to match as close as possible the existing ones, but can easily be changed if wanted.
It should, I hope, also help with future changes to the data layout, as only the extraction of the needed data from the arrays needs to be modified.
I have not done detailed performance tests yet, though the simplicity and likely inlining …
=> Refactor spline calculations into single functions

G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/src/G4HepEmProcess.cc, G4HepEm/src/G4HepEmTrackingManager.cc
This is required for user codes.
Also avoid leaks of dummy processes in G4HepEmProcess.
=> Set ProcessDefinedStep and CreatorProcess in G4HepEmTrackingManager

G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc
In testing AdePT "CPU only" mode using G4HepEm, discovered that use of `G4HepEmTrackingManager` in same fashion as the AdePT tracking manager resulted in a segmentation fault at program exit. This was traced to the destructor of `G4HepEmTrackingManager` deleting the `G4HepEmNoProcess` instances it creates. These are important for mapping back to user code information about the process limiting/creating a step. All tracking managers are deleted by `G4RunManager` _after_ the deletion of `G4ProcessTable` which nominally owns all instances of `G4VProcess`.
Remove deletion of `G4HepEmNoProcess` instances in destructor of `G4HepEmTrackingManager`, leaving their deletion of the destructor of G4ProcessTable. This matches the pattern seen in Geant4's physics constructor classes.
=> Do not delete NoProcess instances in G4HepEmTrackingManager

G4HepEm/G4HepEm/src/G4HepEmProcess.cc
As described in the message of commit ac88af775a, processes are owned by the `G4ProcessTable` and should not be deleted manually. This worked by accident for the `G4HepEmProcess` because it is a process itself which the table deletes before the `G4HepEmNoProcess`es.
=> Do not delete NoProcess instances in G4HepEmProcess

G4HepEm/G4HepEmInit/src/G4HepEmElectronInit.cc
Originally I set the LPM correction flag for the G4 bremsstrahlung models explicitly only for verbosity. This is deprecated now as the LPM flag is taken directly from the `G4EmParameters` in the `Initialise` method of the models. Therefore, we can drop setting the LPM flag in the model explicitly. 
This doesn't change anything regarding the model settings, i.e. the old and new setting is equivalent, leading to exactly the same physics results.
=> Do not set the LPM correction flag for the bremsstrahlung models explicitly.

G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, G4HepEm/G4HepEm/src/TrackingManagerHelper.icc
These are the changes to the `G4HepEmTrackingManager` that are required to provide all functionalities/information for a complete ATLAS Athena simulation. With these modifications, the `G4HepEmTrackingManager` provides e-/e+ and gamma transport simulation inside Athena that agrees well with using the native Geant4 (Atlas patched version of `Geant4-11.2.2`) standard EM physics. This has been checked and verified by performing an ATLAS full physics validation: based on `30 000 ttbar` events simulated in Athena using the native Geant4 standard physics as in production (as ref) v.s. using `G4HepEm`
through this version of the `G4HepEmTrackingManager` (as test).
Some additional modifications are also required though beyond this version of the `G4HepEmTrackingManager` to be used inside ATLAS …
=> Modifications required for using G4HepEm through the G4HepEmTrackingManager inside ATLAS Athena.

G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc
Geant4 fast simulation manager processes, attached to e-/e+ and gamma by the user, were ignored so far in the tracking manager implementation of the stepping loops. These are included now. 
The gamma tracking has been reimplemented without using the stacking manger helper in order to be able to call the fast simulation process and handle that properly during the gamma tracking. 
The code, used both in the e-/e+ and gamma tracking to stack secondaries created by the HepEm physics, is factored now and reused in both places.
=> This adds the capability to the HepEm tracking manger of handling Geant4 fast simulation processes.

G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc
ATLAS has their own, Athena local transition radiation process (XTR) attached to e-/e+. These modifications add the possibility to the tracking manager to find that process at initialisation (based on its name if any) and invoke during e-/e+ tracking in the appropriate way.
NOTE: this implementation cause no harm when such process is not attached to e-/e+, i.e. when the tracking manager is used outside of ATLAS Athena.
=> Add the possibility of involving the ATLAS specific transition radiation process into the e-/e+ tracking.

G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc
Setters, for the name of the transition radiation process and the radiator detector region, have been added (flexibility). Finding the process during the initialisation is activated now. Ready to be used.
=> Finalise the implementation of incorporation the ATLAS specific XTR process.

G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, G4HepEm/G4HepEmData/include/G4HepEmGammaData.hh, G4HepEm/G4HepEmData/src/G4HepEmGammaData.cc, G4HepEm/G4HepEmDataJsonIO/src/G4HepEmDataJsonIOImpl.hh, G4HepEm/G4HepEmInit/include/G4HepEmGammaTableBuilder.hh, G4HepEm/G4HepEmInit/src/G4HepEmGammaInit.cc, G4HepEm/G4HepEmInit/src/G4HepEmGammaTableBuilder.cc, G4HepEm/G4HepEmRun/include/G4HepEmGammaManager.icc, G4HepEm/G4HepEmRun/include/G4HepEmTrack.hh, apps/examples/TestEm3/include/PhysicsList.hh, apps/examples/TestEm3/src/PhysicsList.cc, testing/G4HepEmDataInterfaces/TestG4HepEmDataInterfaces.cc, testing/GammaXSections/include/Declaration.hh, testing/GammaXSections/src/GammaMacXSecs.cu, testing/GammaXSections/src/Implementation.cc, testing/TestUtils/G4HepEmDataComparison.hh
Gamma-nuclear **cross sections are available** now **and used in the HepEm physics during the step limit** calculations for gamma photons. **The interaction** itself **is performed using the corresponding native Geant4 `photonNuclear`, `G4HadronInelasticProcess`** in the HepEm tracking manager: the `PostStepDoIt` of this process is invoked whenever gamma-nuclear limited the step but only if the `photonNuclear` process was attached to gamma in the physics list. 
The HepEm tracking manager tries to find the `photonNuclear` process at initialisation by checking the processes attached to the gamma process manager. If it is found, the pointer to this process is stored locally in the tracking manager such that the process is available during the gamma tracking. If it is not found (i.e. no …
=> Adding gamma-nuclear interaction.

G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, G4HepEm/G4HepEmData/include/G4HepEmElectronData.hh, G4HepEm/G4HepEmData/include/G4HepEmGammaData.hh, G4HepEm/G4HepEmData/src/G4HepEmElectronData.cc, G4HepEm/G4HepEmDataJsonIO/src/G4HepEmDataJsonIOImpl.hh, G4HepEm/G4HepEmInit/include/G4HepEmElectronTableBuilder.hh, G4HepEm/G4HepEmInit/src/G4HepEmElectronInit.cc, G4HepEm/G4HepEmInit/src/G4HepEmElectronTableBuilder.cc, G4HepEm/G4HepEmInit/src/G4HepEmGammaTableBuilder.cc, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, G4HepEm/G4HepEmRun/include/G4HepEmGammaManager.icc, apps/examples/TestEm3/src/PhysicsList.cc, testing/ElectronXSections/include/Declaration.hh, testing/ElectronXSections/src/Implementation.cc, testing/ElectronXSections/src/ResMacXSecs.cu, testing/G4HepEmDataInterfaces/TestG4HepEmDataInterfaces.cc, testing/TestUtils/G4HepEmDataComparison.hh
Electron/positron-nuclear interactions are included now in HepEm. Similarly to gamma-nuclear:
- the cross sections are available in HepEm (both on host and device)
- the cross sections are used during the step limit phase in the HepEm physics 
- but the interactions are not performed inside the HepEm physics: they are done in the HepEmTrackingManager using the native electron/positron-nuclear Geant4 processes (if the user attached to e-/e+ in their physics list)
- everything works fine even if there are no such Geant4 processes attached to the e-/e+  (the particle will stop but keep on moving without any changes).
=> Adding electron/positron-nuclear interactions to HepEm.

G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, G4HepEm/G4HepEmData/include/G4HepEmGammaData.hh, G4HepEm/G4HepEmData/src/G4HepEmGammaData.cc, G4HepEm/G4HepEmDataJsonIO/src/G4HepEmDataJsonIOImpl.hh, G4HepEm/G4HepEmInit/include/G4HepEmGammaTableBuilder.hh, G4HepEm/G4HepEmInit/src/G4HepEmGammaTableBuilder.cc, G4HepEm/G4HepEmRun/include/G4HepEmGammaManager.hh, G4HepEm/G4HepEmRun/include/G4HepEmGammaManager.icc, G4HepEm/G4HepEmRun/include/G4HepEmRunUtils.hh, G4HepEm/G4HepEmRun/include/G4HepEmRunUtils.icc, G4HepEm/G4HepEmRun/include/G4HepEmTrack.hh, apps/examples/TestEm3/ATLASbar.mac, apps/examples/TestEm3/src/PhysListG4Em.cc, testing/G4HepEmDataInterfaces/TestG4HepEmDataInterfaces.cc, testing/GammaTargetElementSelector/src/Implementation.cc, testing/GammaXSections/include/Declaration.hh, testing/GammaXSections/src/GammaMacXSecs.cu, testing/GammaXSections/src/Implementation.cc, testing/TestUtils/G4HepEmDataComparison.hh
Move to a new representation of the gamma cross sections that support using the total macroscopic cross section. This single value is used now to sample the step length till the next interaction, i.e. a single cross section evaluation but without having information on the type of the interaction. The type of the interaction is determined only when interaction indeed happens at that post step point: by further cross section interpolations. This might have benefits in granular geometries when the gamma steps are often limited by volume boundaries thus no physics interaction happens at the post step point. The benefit is due to the reduced number of cross section evaluations.
=> Change the gamma cross section representation.

G4HepEm/G4HepEm/CMakeLists.txt, G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/include/G4HepEmWoodcockHelper.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, G4HepEm/G4HepEm/src/G4HepEmWoodcockHelper.cc, apps/examples/TestEm3/ATLASbar.mac, apps/examples/TestEm3/include/DetectorConstruction.hh, apps/examples/TestEm3/include/DetectorMessenger.hh, apps/examples/TestEm3/src/DetectorConstruction.cc, apps/examples/TestEm3/src/DetectorMessenger.cc, apps/examples/TestEm3/src/PhysListHepEmTracking.cc
Woodcock tracking of photons is used now in the HepEm tracking manager when tracking photons. It can be activated in a detector region by simply adding the detector region name to the HepEm tracking manager using the provided `AddWoodcockTrackingRegion` method.  This can significantly accelerate the simulation in case of sub-detectors with higher granularity when the volume size if smaller then the mean free path, i.e. when photons steps are more often limited by the volume boundary than physics interaction. 
Woodcock tracking of photons is activated now by default in the `TestEm3` example application.
=> Woodcock tracking of photons is available now in the HepEm tracking.    

CMakeLists.txt, G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc
This PR adds the feature of intercepting the tracking loop of `TrackElectron` and `TrackGamma` in the `G4HepEmTrackingManager`. Via the compile-time flag `G4HepEm_EARLY_TRACKING_EXIT` a new virtual function `CheckEarlyTrackingExit` is introduced. If that function returns true, the tracking loop is exited immediately. It is up to the user in the derived class to handle the proper ending of the track. Therefore few parameters needed to be set to `protected` instead of `private`. 
This feature allows for exiting the tracking loop to, e.g., track particles on GPU, as shown in the derived `G4HepEmTrackingManagerSpecialized` class in [this PR in AdePT ](https://github.com/apt-sim/AdePT/pull/324).
=> Add early tracking exit

G4HepEm/G4HepEmData/include/G4HepEmMatCutData.hh, G4HepEm/G4HepEmDataJsonIO/src/G4HepEmDataJsonIOImpl.hh, G4HepEm/G4HepEmInit/src/G4HepEmMaterialInit.cc, testing/MaterialAndRelated/src/Implementation.cc, testing/MaterialAndRelated/src/MatCutData.cu, testing/TestUtils/G4HepEmDataComparison.hh
Secondary positron production values are not used at the moment in the run time part of `G4HepEm` (`G4HepEmRun`) but we added now them to the material cut data to make them available on the device. This can be used now to implement `applyCut` also on the device (similarly as done in the `G4HepEmTrackingManager` based directly on the `Geant4` values).
=> Storing and making available the secondary e+ production energy threshold values also on the device now.

G4HepEm/G4HepEm/CMakeLists.txt, G4HepEm/G4HepEm/include/G4HepEmConfig.hh, G4HepEm/G4HepEm/include/G4HepEmRunManager.hh, G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/include/G4HepEmWoodcockHelper.hh, G4HepEm/G4HepEm/src/G4HepEmConfig.cc, G4HepEm/G4HepEm/src/G4HepEmRunManager.cc, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, G4HepEm/G4HepEmData/CMakeLists.txt, G4HepEm/G4HepEmData/include/G4HepEmMatCutData.hh, G4HepEm/G4HepEmData/include/G4HepEmParameters.hh, G4HepEm/G4HepEmData/src/G4HepEmParameters.cc, G4HepEm/G4HepEmDataJsonIO/src/G4HepEmDataJsonIOImpl.hh, G4HepEm/G4HepEmInit/include/G4HepEmElectronInit.hh, G4HepEm/G4HepEmInit/include/G4HepEmGammaInit.hh, G4HepEm/G4HepEmInit/src/G4HepEmElectronInit.cc, G4HepEm/G4HepEmInit/src/G4HepEmGammaInit.cc, G4HepEm/G4HepEmInit/src/G4HepEmMaterialInit.cc, G4HepEm/G4HepEmInit/src/G4HepEmParametersInit.cc, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionUMSC.hh, G4HepEm/G4HepEmRun/include/G4HepEmElectronInteractionUMSC.icc, G4HepEm/G4HepEmRun/include/G4HepEmElectronManager.icc, apps/examples/TestEm3/src/PhysListHepEmTracking.cc, testing/G4HepEmDataInterfaces/TestG4HepEmDataInterfaces.cc, testing/TestUtils/G4HepEmDataComparison.hh
A `G4HepEmConfig` object has been added to the `G4HepEmTrackingManager` that allows to set and store configuration options and parameters. Most of the parameters are stored in its `G4HepEmParameters` member that has been extended to hold some of its parameters per detector region.
The `G4HepEmConfig` member of the `G4HepEmTrackingManager` can be obtained after its construction and its parameters can be set before the initialisation of the run. 
Different values of the following parameters can be set per detector region using the `G4HepEmConfig` setters:
- Woodcock tracking of photons and its kinetic energy limit (below which it's turned OFF)
(default: Woodcock tracking is OFF; its minimal energy is `200 keV`) 
- parameters of the continuous energy loss step limit function 
(default: …
=> Adding configuration options, allowing some to be set per detector region.

G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, G4HepEm/G4HepEm/src/G4HepEmWoodcockHelper.cc
A set of final modifications correcting some issues (e.g. correct setting of the creator process in case of gamma interactions or ensuring to find the gamma-nuclear interaction even if encapsulated inside the gamma-general process), increasing robustness (e.g. detect if Woodcock tracking was required in non-leaf detector region or allowing the ATLAS specific `XTR` process work even if no special region has been set for it). Report on the extra process configuration, i.e. on fast simulation and nuclear interactions, has also been added.
=> A set of smaller modifications for increasing robustness and verbosity.

G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc, apps/examples/TestEm3/ATLASbar.mac, apps/examples/TestEm3/include/PhysicsListMessenger.hh, apps/examples/TestEm3/src/G4HepEmProcess.cc, apps/examples/TestEm3/src/PhysListHepEm.cc, apps/examples/TestEm3/src/PhysListHepEmTracking.cc, apps/examples/TestEm3/src/PhysicsList.cc, apps/examples/TestEm3/src/PhysicsListMessenger.cc
Most of the modifications are related to the verbosity level of the physics (list) configuration/parameter report and its setting. This can now be controlled by a UI command. An additional, unrelated modification is that the `G4HepEmProcess`, i.e. connecting only the `G4HepEm` physics to `Geant4` through its `G4VProcess` interface, has been recovered and works again as expected (after the recent changes in the gamma cross sections). However, `G4HepEm` should be connected to `Geant4` and used only through its `G4HepEmTrackingManager` as this is the only complete and efficient way of its utilisation (the process interface was used only during the physics development).
=> Miscellaneous modifications on the example application. 

G4HepEm/G4HepEm/CMakeLists.txt
`G4HepEmTrackingManager.cc` now includes `G4GammaGeneralProcess.hh`, which is part of the `G4physicslists` library. This fixes the compilation with a build directory of Geant4 (non-installed).
=> Link against `Geant4::G4physicslists`

G4HepEm/G4HepEm/include/G4HepEmTrackingManager.hh, G4HepEm/G4HepEm/src/G4HepEmTrackingManager.cc
Nuclear (gamma/electron/positron) interactions can be invoked now easily using the `PerformNuclear` method, even from outside of the `G4HepEmTrackingManager`, making them available for external users as well. 
The type of the interaction is determined by the `partileID` input argument(={2/0/1} --> gamma/electron/positron - nuclear). The corresponding `G4HadronInelasticProcess` is invoked, the input track and step are updated, the secondaries are stacked to the secondary track vector of the input step and the energy deposited during the interaction (or due to applying the cuts on the secondaries) is returned. The method is self contained, i.e. includes all preparations required to perform the interactions.  
Additional methods are provided to make the pointers of the …
=> Factor out nuclear interactions: available now for external users. 
